# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'TileGame' do
  
pod ‘ChameleonFramework’

pod ‘ImageFilesPicker'
pod 'FCFileManager'
pod 'MagicalRecord'

end
